<a href="https://colab.research.google.com/github/pavithra64/ML-data-cleaning/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PROGRAM USING NUMPY**

In [1]:
import numpy as np
print("Creating array using numpy")
a=np.array(10)
b=np.array([10.0,20.0,45.0,64.0,72.5])
c=np.array([[10,20,30],[40,50,100]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[4,3,2]]])
print("Creating array with range function")
ar1=np.arange(10)
print(ar1)
ar2=np.arange(1,11)
print(ar2)
ar3=np.arange(10,30,2)
print(ar3)
ar4=np.arange(-20,6,5)
print(ar4)
print("Creating 1-D array with zero values")
array1=np.zeros(5)
print(array1)
print("Creating 2-D array with zero values")
array2=np.zeros((2,3))
print(array2)
print("Creating 3-D array with zero values")
array3=np.zeros((4,3,5))
print(array3)
print("Creating 1-D array with full function")
array_1=np.full(shape=5, fill_value=6)
print(array_1)
print("Creating 2-D array with zero values")
array_2=np.full(shape=(2,3),fill_value=8)
print(array_2)
print("Creating 3-D array with zero values")
array_3=np.full(shape=(4,3,5),fill_value=3)
print(array_3)
print("Display the content of different arrays")
print(a)
print(b)
print(c)
print(d)
print("Type and Dimensions of different arrays")
print("Type of array a=",type(a))
print("Dimension of array a=",a.ndim)
print("Dimension of array b=",b.ndim)
print("Dimension of array c=",c.ndim)
print("Dimension of array d=",d.ndim)
print("properties of array")
print("Data type of array a=",a.dtype)
print("Data type of array b=",b.dtype)
print("Size of different arrays")
print("Size of array a=",a.shape)
print("Size of array b=",b.shape)
print("Size of array c=",c.shape)
print("Size of array d=",d.shape)
print("Memory space require to store each element in array a=",a.itemsize)
print("Memory space require to store each element in array b=",b.itemsize)
print("change the dimension of array")
print(c.reshape(3,2))
print("Statistical functions using array")
a1=np.array([[4,8],[6,12]])
b1=np.mean(a1,axis=0)
b2=np.mean(a1,axis=1)
print("Mean releated with axis 0=",b1)
print("Mean releated with axis 1=",b2)
a2=np.array([[1,4,5,6],[3,5,7,8],[8,9,6,5]])
c1=np.median(a2,axis=0)
c2=np.median(a2,axis=1)
print("Median releated with axis 0=",c1)
print("Median releated with axis 1=",c2)
c3=np.std(a2,axis=0)
print("Standard deviation of array a2 related with axis 0=",c3)
print("inserting data inside the existing array");
i=np.array([[3,5],[9,8]])
j=np.array([[10,12],[21,22]])
k=np.append(i,j)
print(k)
print("broadcasting of value in specific axis of an array")
m=np.array([[1,5],[2,4],[3,6],[8,9]])
print(np.insert(m,2,[9],axis=0))
print(np.insert(m,2,[9],axis=1))
print(np.insert(m,1,[9],axis=1))
print("Concatenation of two arrays")
i1=np.array([[6,7],[8,9]])
j1=np.array([[1,2]])
k1=np.concatenate((i1,j1))
print(k1)
print("Mathamatical function using NumPy")
print("Addition of two arrays")
print(i+j)
print("Alternative approch")
print(np.add(i,j))
print("Substraction of two arrays")
print(i-j)
print("Alternative approch")
print(np.subtract(i,j))
print("Multiplication of two arrays")
print(i*j)
print("Alternative approch")
print(np.multiply(i,j))
print("division of two arrays")
print(i/j)
print("Alternative approch")
print(np.divide(i,j))
print("creating array with random value between 0 and 1")
i3=np.random.rand(3,3)
print(i3)
print("Soted array content:")
s_arr=np.sort(k)
print(s_arr)
print("Accessing array elements using index")
print("Second element in array b=",b[0])
print("The value of second element in second row in array c=",c[1][1])
print("last element in First row of array c=",c[0,-1])
print("last element in Second row of array c=",c[1,-1])
print("Accessing 3 dimensional array content:")
print(d[0,1,2])
print("1-D Array  with slice function")
print(b[1:4])
print(b[:3])
print(b[2:5])
print(b[-4:-2])
print("2-D Array  with slice function")
print(c[0:,0:1])
print("3-D Array  with slice function")
print(d[0,1,0:2])



Creating array using numpy
Creating array with range function
[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[10 12 14 16 18 20 22 24 26 28]
[-20 -15 -10  -5   0   5]
Creating 1-D array with zero values
[0. 0. 0. 0. 0.]
Creating 2-D array with zero values
[[0. 0. 0.]
 [0. 0. 0.]]
Creating 3-D array with zero values
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
Creating 1-D array with full function
[6 6 6 6 6]
Creating 2-D array with zero values
[[8 8 8]
 [8 8 8]]
Creating 3-D array with zero values
[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]
Display the content of different arrays
10
[10.  20.  45.  64.  72.5]
[[ 10  20  30]
 [ 40  50 100]]
[[[1 2 3]
  [4 5 6]]

